name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # 3. Build JAR file using Maven Wrapper (for Windows)
      - name: Build JAR with Maven
        working-directory: example_22
        shell: cmd
        run: |
          call mvnw.cmd clean package -DskipTests

      # 4. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 5. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Build and push Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./example_22
          file: ./example_22/Dockerfile
          push: true
          tags: quang042000/example22:latest

      # 7. Restart Docker container (Windows compatible)
      - name: Restart Docker container
        shell: cmd
        run: |
          docker stop example-container || exit 0
          docker rm example-container || exit 0
          docker pull quang042000/example22:latest
          docker run -d -p 8080:8080 --name example-container quang042000/example22:latest

          
