name: Deploy Spring Boot Docker to VPS

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR file
        run: |
          cd example_22
          ./mvnw clean package -DskipTests

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "example_22/target/example_22-0.0.1-SNAPSHOT.jar,example_22/Dockerfile"
          target: "/home/root/app"

      - name: Run Docker commands on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/root/app
            docker stop example22-container || true
            docker rm example22-container || true
            docker rmi example22:latest || true
            docker build --no-cache -t example22:latest .
            docker run -d -p 8080:8080 --name example22-container example22:latest
