name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Build .jar file using Maven Wrapper
      - name: Run Docker container locally
        shell: pwsh
        run: |
         docker stop example22-container 2>$null
         docker rm example22-container 2>$null
         docker run -d -p 80:8080 --name example22-container quang042000/example22:latest


      # 4. Set up Docker Buildx (nên setup trước build image)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 5. (Tùy chọn) Login Docker Hub nếu bạn vẫn muốn push lên Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Build & Push Docker Image (vẫn push lên Docker Hub nếu bạn muốn)
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./example_22
          file: ./example_22/Dockerfile
          push: true
          tags: quang042000/example22:latest

      # 7. Run Docker container locally
      - name: Run Docker container locally
        run: |
          docker stop example22-container || true
          docker rm example22-container || true
          docker pull quang042000/example22:latest
          docker run -d -p 80:8080 --name example22-container quang042000/example22:latest

          
